apiVersion: v1
kind: Service
metadata:
    name: bioaps
    namespace: bioaps
    labels:
        app: bioaps
        tier: frontend
spec:
    type: NodePort
    ports:
        - port: 5000
    selector:
        app: bioaps
        tier: frontend

---

apiVersion: cloud.google.com/v1beta1
kind: BackendConfig
metadata:
    name: bioaps-service-backendconfig
    namespace: bioaps
spec:
    timeoutSec: 80000
    connectionDraining:
        drainingTimeoutSec: 3600 # time to complete connections
