apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: bioaps-hpa
  namespace: bioaps
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: bioaps-deployment
  minReplicas: 1
  maxReplicas: 3
  targetCPUUtilizationPercentage: 70