apiVersion: v1
kind: Service
metadata:
    name: babi
    namespace: babi
    labels:
        app: babi
        tier: frontend
spec:
    type: NodePort
    ports:
        - port: 5000
    selector:
        app: babi
        tier: frontend

---

apiVersion: cloud.google.com/v1beta1
kind: BackendConfig
metadata:
    name: stg-babi-service-backendconfig
    namespace: babi
spec:
    timeoutSec: 80000
    connectionDraining:
        drainingTimeoutSec: 3600 # time to complete connections
