apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: stg-babi-hpa
  namespace: babi
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: stg-babi-deployment
  minReplicas: 1
  maxReplicas: 3
  targetCPUUtilizationPercentage: 70